project:
  type: website

website:
  title: "Aiden Roach's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"

format:
  html:
    theme: jolla
    css: styles.css
    toc: true

editor: visual

