project:
  type: website
  output-dir: docs

website:
  title: "Aiden Roach's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      #- href: about.qmd
       # text: "About Me"
      - href: woodrat.qmd
        text: "Woodrat Study"
      - href: urchin.qmd
        text: "Purple Urchin Study"
      - href: case_study.qmd
        text: "Ringtail Case Study"
      - href: capstone.qmd
        text: "Capstone"
      - href: qfm.qmd
        text: "Other Papers"
format:
  html:
    theme: Superhero
    css: styles.css
    toc: true

editor: visual

