project:
  type: website
  output-dir: docs

website:
  title: "Aiden Roach's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: posters.qmd
        text: "Posters"
      - text: "Papers"
        menu: 
        - href: case_study.qmd
        - text: " Ringtail Case Study"
        - href: urchin.qmd
        - text: "Purple Urchin Experiment"
format:
  html:
    theme: Superhero
    css: styles.css
    toc: true

editor: visual

